language: node_js
node_js:
  - 6
addons:
    code_climate:
        repo_token: $CODECLIMATE_REPO_TOKEN
cache:
  directories:
    - node_modules
before_script:
  - npm install codeclimate-test-reporter istanbul -g
script:
  - CI=false npm run build
  - istanbul cover npm test
after_script: # Upload coverage reports 
  - codeclimate-test-reporter < ./coverage/lcov.info